# Generated by Django 5.1.3 on 2025-03-06 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_date',
        ),
    ]
